"""reset tables

Revision ID: 2c635e06b000
Revises: 
Create Date: 2025-08-28 19:57:15.850813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c635e06b000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('COMPRADOR', 'VENDEDOR', name='tipousuario'), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('produtos',
    sa.Column('produto_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('imagem', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.user_id'], ),
    sa.PrimaryKeyConstraint('produto_id')
    )
    op.create_table('compras',
    sa.Column('compra_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comprador_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('data_compra', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comprador_id'], ['usuarios.user_id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.produto_id'], ),
    sa.PrimaryKeyConstraint('compra_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compras')
    op.drop_table('produtos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
