"""adicao de imagem em produto

Revision ID: 1cc6bda8b3ea
Revises: d2f969b6f92d
Create Date: 2025-08-28 10:06:14.025922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc6bda8b3ea'
down_revision = 'd2f969b6f92d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=100), nullable=False))
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
